import { KAIGO_SERVICE_NAME, KAIGO_SYSTEM_PROMPT } from '@/features/kaigo/constants';

export const TOP_CHAT_SYSTEM_PROMPT =
  import.meta.env.VITE_APP_TOP_CHAT_SYSTEM_PROMPT ?? KAIGO_SYSTEM_PROMPT;
export const TOP_CHAT_SYSTEM_PROMPT_TITLE =
  import.meta.env.VITE_APP_TOP_CHAT_SYSTEM_PROMPT_TITLE ?? KAIGO_SERVICE_NAME;
